import express from "express";
import multer from "multer";
import { Candidate, JobOpening, Employee } from "../models/index.js";
import { requireAuth } from "../middleware/auth.js";
import { ok, fail, pageMeta } from "../utils/http.js";
import { makeId } from "../utils/ids.js";
import { saveUploadedFile } from "../services/storageService.js";
import { readRows, resolveColumns, valueFor, cleanText } from "../utils/bulkSpreadsheet.js";

const router=express.Router(), upload=multer({storage:multer.memoryStorage(),limits:{fileSize:15*1024*1024}}); router.use(requireAuth);
router.use((req,res,next)=>{if(req.auth?.role==="MASTER"||(req.auth?.apps||[]).includes("hr"))return next();return fail(res,"HR access required",403);});
router.get("/dashboard",async(req,res)=>{const tenantKey=req.auth.tenantKey;const [openJobs,candidates,shortlisted,interviews,selected,joined]=await Promise.all([JobOpening.countDocuments({tenantKey,status:{$in:["APPROVED","OPEN"]}}),Candidate.countDocuments({tenantKey}),Candidate.countDocuments({tenantKey,stage:"SHORTLISTED"}),Candidate.countDocuments({tenantKey,stage:"INTERVIEW"}),Candidate.countDocuments({tenantKey,stage:"SELECTED"}),Candidate.countDocuments({tenantKey,stage:"JOINED"})]);ok(res,{openJobs,candidates,shortlisted,interviews,selected,joined});});
router.get("/jobs",async(req,res)=>{const items=await JobOpening.find({tenantKey:req.auth.tenantKey}).sort({createdAt:-1}).lean();ok(res,items);});
router.post("/jobs",async(req,res)=>{if(!req.body.title)return fail(res,"Job title is required");const job=await JobOpening.create({...req.body,tenantKey:req.auth.tenantKey,jobId:req.body.jobId||makeId("JOB"),createdBy:req.auth.sub});ok(res,job,"Job opening created",201);});
router.put("/jobs/:id",async(req,res)=>{const job=await JobOpening.findOneAndUpdate({_id:req.params.id,tenantKey:req.auth.tenantKey},req.body,{new:true,runValidators:true});if(!job)return fail(res,"Job not found",404);ok(res,job,"Job updated");});
router.delete("/jobs/:id",async(req,res)=>{const job=await JobOpening.findOneAndDelete({_id:req.params.id,tenantKey:req.auth.tenantKey});if(!job)return fail(res,"Job not found",404);ok(res,{deleted:true},"Job deleted");});

router.post("/candidates/bulk-upload",upload.single("file"),async(req,res)=>{
  if(!req.file?.buffer)return fail(res,"Excel/CSV file is required",400);
  let rows;try{rows=readRows(req.file.buffer);}catch{return fail(res,"Unable to read Excel/CSV file",400);}if(!rows.length)return fail(res,"Uploaded file has no rows",400);
  const fields=[{key:"name",label:"Candidate Name",aliases:["name"],required:true},{key:"mobile",label:"Mobile"},{key:"email",label:"Email"},{key:"jobId",label:"Job ID"},{key:"source",label:"Source"},{key:"city",label:"City"},{key:"pincode",label:"Pincode"},{key:"address",label:"Address"},{key:"education",label:"Education"},{key:"experience",label:"Experience"},{key:"currentCompany",label:"Current Company"},{key:"currentSalary",label:"Current Salary",type:"number"},{key:"expectedSalary",label:"Expected Salary",type:"number"},{key:"noticePeriod",label:"Notice Period"},{key:"preferredLocation",label:"Preferred Location"},{key:"skills",label:"Skills"},{key:"languages",label:"Languages"},{key:"stage",label:"Stage"},{key:"fitScore",label:"Fit Score",type:"number"}];
  const cols=resolveColumns(rows[0],fields);if(!cols.name)return fail(res,"Missing column: Candidate Name",400);
  const errors=[];let inserted=0,duplicates=0;
  for(let i=0;i<rows.length;i++){
    const r={};for(const f of fields){const v=valueFor(rows[i],cols[f.key],f.type);if(v!==undefined&&v!=="")r[f.key]=v;}if(!r.name){if(errors.length<100)errors.push({row:i+2,error:"Candidate Name is required"});continue;}
    const mobile=cleanText(r.mobile),email=cleanText(r.email).toLowerCase();const clauses=[];if(mobile)clauses.push({mobile});if(email)clauses.push({email});
    if(clauses.length&&await Candidate.exists({tenantKey:req.auth.tenantKey,$or:clauses})){duplicates++;continue;}
    try{await Candidate.create({...r,tenantKey:req.auth.tenantKey,candidateId:makeId("CAN"),mobile,email:email||undefined,stage:String(r.stage||"NEW").toUpperCase(),skills:String(r.skills||"").split(/[,;]+/).map(x=>x.trim()).filter(Boolean),languages:String(r.languages||"").split(/[,;]+/).map(x=>x.trim()).filter(Boolean),currentSalary:Number(r.currentSalary||0),expectedSalary:Number(r.expectedSalary||0),fitScore:Number(r.fitScore||0)});inserted++;}
    catch(e){if(errors.length<100)errors.push({row:i+2,error:e.message});}
  }
  ok(res,{received:rows.length,inserted,duplicates,invalid:errors.length,errors},"Candidate bulk upload completed");
});
router.post("/candidates/bulk-edit",async(req,res)=>{const ids=(req.body.selection?.ids||[]).filter(Boolean);if(!ids.length)return fail(res,"Select at least one candidate",400);const allowed=["jobId","source","city","preferredLocation","stage","fitScore"];const changes={};for(const k of allowed)if(req.body.changes?.[k]!==undefined&&req.body.changes[k]!=="")changes[k]=req.body.changes[k];if(changes.stage)changes.stage=String(changes.stage).toUpperCase();if(changes.fitScore!==undefined)changes.fitScore=Number(changes.fitScore);if(!Object.keys(changes).length)return fail(res,"Enter at least one value to change",400);const result=await Candidate.updateMany({_id:{$in:ids},tenantKey:req.auth.tenantKey,stage:{$ne:"JOINED"}},{$set:changes},{runValidators:true});ok(res,{matched:result.matchedCount,updated:result.modifiedCount},`${result.modifiedCount} candidate(s) updated`);});
router.post("/candidates/bulk-delete",async(req,res)=>{const ids=(req.body.selection?.ids||[]).filter(Boolean);if(!ids.length)return fail(res,"Select at least one candidate",400);const result=await Candidate.deleteMany({_id:{$in:ids},tenantKey:req.auth.tenantKey,stage:{$ne:"JOINED"}});ok(res,{deleted:result.deletedCount},`${result.deletedCount} candidate(s) deleted. Joined candidates were protected.`);});

router.get("/candidates",async(req,res)=>{const page=Number(req.query.page||1),limit=Math.min(200,Number(req.query.limit||50)),q=String(req.query.q||"").trim(),f={tenantKey:req.auth.tenantKey};if(req.query.stage)f.stage=req.query.stage;if(req.query.jobId)f.jobId=req.query.jobId;if(q)f.$or=[{name:new RegExp(q,"i")},{mobile:new RegExp(q,"i")},{email:new RegExp(q,"i")},{candidateId:new RegExp(q,"i")}];const[items,total]=await Promise.all([Candidate.find(f).sort({updatedAt:-1}).skip((page-1)*limit).limit(limit).lean(),Candidate.countDocuments(f)]);ok(res,{items,meta:pageMeta(page,limit,total)});});
router.post("/candidates",async(req,res)=>{if(!req.body.name)return fail(res,"Candidate name is required");const dupe=await Candidate.findOne({tenantKey:req.auth.tenantKey,$or:[req.body.mobile?{mobile:req.body.mobile}:null,req.body.email?{email:String(req.body.email).toLowerCase()}:null].filter(Boolean)});if(dupe)return fail(res,"Candidate already exists with the same mobile/email",409,{candidateId:dupe.candidateId});const c=await Candidate.create({...req.body,email:req.body.email?String(req.body.email).toLowerCase():undefined,tenantKey:req.auth.tenantKey,candidateId:req.body.candidateId||makeId("CAN")});ok(res,c,"Candidate created",201);});
router.put("/candidates/:id",async(req,res)=>{const c=await Candidate.findOneAndUpdate({_id:req.params.id,tenantKey:req.auth.tenantKey},req.body,{new:true,runValidators:true});if(!c)return fail(res,"Candidate not found",404);ok(res,c,"Candidate updated");});
router.post("/candidates/:id/stage",async(req,res)=>{const c=await Candidate.findOne({_id:req.params.id,tenantKey:req.auth.tenantKey});if(!c)return fail(res,"Candidate not found",404);c.stage=req.body.stage||c.stage;if(req.body.interviewRound)c.interviewRounds.push({...req.body.interviewRound,date:req.body.interviewRound.date?new Date(req.body.interviewRound.date):new Date()});if(req.body.fitScore!=null)c.fitScore=Number(req.body.fitScore);await c.save();ok(res,c,"Candidate stage updated");});
router.post("/candidates/:id/resume",upload.single("file"),async(req,res)=>{if(!req.file)return fail(res,"Resume file required");const c=await Candidate.findOne({_id:req.params.id,tenantKey:req.auth.tenantKey});if(!c)return fail(res,"Candidate not found",404);const meta=await saveUploadedFile({file:req.file,tenantKey:req.auth.tenantKey,module:"HR",entityType:"CANDIDATE",entityId:c.candidateId,uploadedBy:req.auth.sub,access:"PRIVATE"});c.resumeFileId=meta.fileId;await c.save();ok(res,{candidate:c,file:meta},"Resume uploaded");});
router.post("/candidates/:id/join",async(req,res)=>{const c=await Candidate.findOne({_id:req.params.id,tenantKey:req.auth.tenantKey});if(!c)return fail(res,"Candidate not found",404);if(c.employeeId)return fail(res,"Candidate is already linked to an employee",409);const employee=await Employee.create({tenantKey:req.auth.tenantKey,employeeId:makeId("EMP"),name:c.name,mobile:c.mobile,email:c.email,department:req.body.department||"",designation:req.body.designation||"",joiningDate:req.body.joiningDate||new Date(),salary:Number(req.body.salary||c.offer?.salary||0),status:"ACTIVE"});c.employeeId=employee.employeeId;c.stage="JOINED";await c.save();ok(res,{candidate:c,employee},"Candidate joined and employee created",201);});
export default router;
