import PDFDocument from "pdfkit";

const ascii = (value) => String(value ?? "")
  .replace(/₹/g, "INR ")
  .normalize("NFKD")
  .replace(/[^\x20-\x7E]/g, "?");

const escapePdf = (value) => ascii(value)
  .replace(/\\/g, "\\\\")
  .replace(/\(/g, "\\(")
  .replace(/\)/g, "\\)");

function wrapLine(text, max = 92) {
  const value = ascii(text);
  if (value.length <= max) return [value];
  const words = value.split(/\s+/);
  const out = [];
  let line = "";
  for (const word of words) {
    if (!line) line = word;
    else if (`${line} ${word}`.length <= max) line += ` ${word}`;
    else { out.push(line); line = word; }
  }
  if (line) out.push(line);
  return out;
}

export function buildTextPdf({ title = "Document", lines = [], footer = "Generated by Rupioo Global" } = {}) {
  const source = [title, "", ...lines, "", footer];
  const wrapped = source.flatMap((line) => wrapLine(line));
  const perPage = 52;
  const pages = [];
  for (let i = 0; i < wrapped.length; i += perPage) pages.push(wrapped.slice(i, i + perPage));
  if (!pages.length) pages.push([title]);

  const objects = new Map();
  const pageRefs = [];
  objects.set(1, `<< /Type /Catalog /Pages 2 0 R >>`);
  objects.set(3, `<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`);

  pages.forEach((pageLines, index) => {
    const pageNo = 4 + index * 2;
    const streamNo = pageNo + 1;
    pageRefs.push(`${pageNo} 0 R`);
    const commands = ["BT", "/F1 9 Tf", "42 802 Td", "12 TL"];
    pageLines.forEach((line, lineIndex) => {
      if (lineIndex > 0) commands.push("T*");
      commands.push(`(${escapePdf(line)}) Tj`);
    });
    commands.push("ET");
    const stream = commands.join("\n");
    objects.set(pageNo, `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 3 0 R >> >> /Contents ${streamNo} 0 R >>`);
    objects.set(streamNo, `<< /Length ${Buffer.byteLength(stream, "utf8")} >>\nstream\n${stream}\nendstream`);
  });
  objects.set(2, `<< /Type /Pages /Kids [${pageRefs.join(" ")}] /Count ${pages.length} >>`);

  const maxObject = Math.max(...objects.keys());
  let pdf = "%PDF-1.4\n%RUPIOO\n";
  const offsets = new Array(maxObject + 1).fill(0);
  for (let i = 1; i <= maxObject; i += 1) {
    offsets[i] = Buffer.byteLength(pdf, "utf8");
    pdf += `${i} 0 obj\n${objects.get(i) || "<<>>"}\nendobj\n`;
  }
  const xref = Buffer.byteLength(pdf, "utf8");
  pdf += `xref\n0 ${maxObject + 1}\n`;
  pdf += "0000000000 65535 f \n";
  for (let i = 1; i <= maxObject; i += 1) pdf += `${String(offsets[i]).padStart(10, "0")} 00000 n \n`;
  pdf += `trailer\n<< /Size ${maxObject + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;
  return Buffer.from(pdf, "utf8");
}

const money = (value) => Number(value || 0).toFixed(2);

export function buildSalesInvoicePdf({ invoice, company, customer, delivery } = {}) {
  const lines = [
    company?.companyName || company?.tradeName || "Company",
    company?.registeredAddress || "",
    company?.gstin ? `GSTIN: ${company.gstin}` : "",
    "",
    `Invoice No: ${invoice?.invoiceNo || ""}`,
    `Invoice Date: ${invoice?.date ? new Date(invoice.date).toLocaleDateString("en-IN") : ""}`,
    `Customer: ${invoice?.customerNameSnapshot || customer?.localName || ""}`,
    invoice?.gstinSnapshot ? `Customer GSTIN: ${invoice.gstinSnapshot}` : "",
    invoice?.addressSnapshot ? `Bill/Ship Address: ${invoice.addressSnapshot}` : "",
    invoice?.transportAssignment?.mode && invoice.transportAssignment.mode!=="LOCAL" ? `Transporter: ${invoice.transportAssignment.transporterNameSnapshot||""}` : "",
    invoice?.transportAssignment?.bookingStationNameSnapshot ? `Booking Station: ${invoice.transportAssignment.bookingStationNameSnapshot}${invoice.transportAssignment.bookingStationCitySnapshot?` - ${invoice.transportAssignment.bookingStationCitySnapshot}`:""}` : "",
    invoice?.transportAssignment?.deliveryStationNameSnapshot ? `Delivery Station: ${invoice.transportAssignment.deliveryStationNameSnapshot}${invoice.transportAssignment.deliveryStationCitySnapshot?` - ${invoice.transportAssignment.deliveryStationCitySnapshot}`:""}${invoice.transportAssignment.deliveryStationPincodeSnapshot?` (${invoice.transportAssignment.deliveryStationPincodeSnapshot})`:""}` : "",
    "",
    "ITEMS",
    ...(invoice?.items || []).flatMap((item, index) => [
      `${index + 1}. ${item.nameSnapshot || item.sku || "Product"}`,
      `   Qty ${money(item.qty)} ${item.unit || ""} | Rate ${money(item.effectiveRate ?? item.rate)} | GST ${money(item.gstRateSnapshot)}% | Total ${money(item.lineTotal)}`,
    ]),
    "",
    `Taxable Total: INR ${money(invoice?.taxableTotal)}`,
    `GST Total: INR ${money(invoice?.taxTotal)}`,
    `Round Off: INR ${money(invoice?.roundOff)}`,
    `Grand Total: INR ${money(invoice?.grandTotal)}`,
  ];
  if (delivery) {
    lines.push(
      "",
      "DELIVERY DETAILS",
      `Delivered At: ${delivery.deliveredAt ? new Date(delivery.deliveredAt).toLocaleString("en-IN") : ""}`,
      `Delivered To: ${delivery.deliveredTo || ""}`,
      delivery.mobile ? `Mobile: ${delivery.mobile}` : "",
      delivery.vehicleNo ? `Vehicle No: ${delivery.vehicleNo}` : "",
      delivery.biltyNo ? `Bilty/LR No: ${delivery.biltyNo}` : "",
      delivery.remarks ? `Remarks: ${delivery.remarks}` : "",
    );
  }
  return buildTextPdf({ title: `TAX INVOICE - ${invoice?.invoiceNo || ""}`, lines: lines.filter(Boolean) });
}

export async function buildLedgerPdf({ company, customer, financialYear, entries = [], summary = {}, opening = {} } = {}) {
  const doc = new PDFDocument({ size: "A4", margin: 34, bufferPages: true });
  const chunks = [];
  doc.on("data", (chunk) => chunks.push(chunk));
  const completed = new Promise((resolve, reject) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });

  const pageWidth = doc.page.width;
  const margin = 34;
  const usableWidth = pageWidth - margin * 2;
  const widths = [60, 190, 80, 70, 62, 62];
  const headers = ["Date", "Particular", "Voucher Type", "Voucher No", "Debit", "Credit"];
  const fmt = (value) => Number(value || 0).toFixed(2);
  const dateText = (value) => {
    if (!value) return "";
    const d = new Date(value);
    return Number.isNaN(d.getTime()) ? String(value).slice(0, 10) : d.toLocaleDateString("en-GB");
  };

  const companyName = company?.companyName || company?.tradeName || "Company";
  const partyName = customer?.localName || customer?.name || "Party";

  const drawCenteredHeader = () => {
    doc.font("Helvetica-Bold").fontSize(7.5).fillColor("#374151")
      .text("THIS LEDGER IS GENERATED IN RUPIO SOFT", margin, 24, { width: usableWidth, align: "center" });
    let y = 39;
    doc.font("Helvetica-Bold").fontSize(14).fillColor("#111827")
      .text(companyName, margin, y, { width: usableWidth, align: "center" });
    y = doc.y + 3;
    doc.font("Helvetica").fontSize(8.5).fillColor("#4B5563");
    if (company?.registeredAddress) {
      doc.text(String(company.registeredAddress), margin, y, { width: usableWidth, align: "center" });
      y = doc.y + 2;
    }
    const contact = [company?.email, company?.mobile].filter(Boolean).join("  |  ");
    if (contact) {
      doc.text(contact, margin, y, { width: usableWidth, align: "center" });
      y = doc.y + 2;
    }
    if (company?.gstin) {
      doc.text(`GSTIN: ${company.gstin}`, margin, y, { width: usableWidth, align: "center" });
      y = doc.y + 2;
    }
    doc.font("Helvetica-Bold").fontSize(12).fillColor("#111827")
      .text(`${partyName} - Ledger${financialYear ? ` (${financialYear})` : ""}`, margin, y + 5, { width: usableWidth, align: "center" });
    return doc.y + 10;
  };

  const drawCell = (text, x, y, width, height, opts = {}) => {
    doc.rect(x, y, width, height).strokeColor("#D1D5DB").lineWidth(0.5).stroke();
    doc.font(opts.bold ? "Helvetica-Bold" : "Helvetica")
      .fontSize(opts.fontSize || 8.2)
      .fillColor(opts.color || "#111827")
      .text(String(text ?? ""), x + 4, y + 4, {
        width: width - 8,
        height: height - 8,
        align: opts.align || "left",
        ellipsis: true,
        lineBreak: true,
      });
  };

  const drawTableHeader = (y) => {
    let x = margin;
    headers.forEach((header, i) => {
      doc.rect(x, y, widths[i], 22).fillAndStroke("#F3F4F6", "#D1D5DB");
      doc.font("Helvetica-Bold").fontSize(7.5).fillColor("#111827")
        .text(header, x + 3, y + 7, { width: widths[i] - 6, align: "center" });
      x += widths[i];
    });
    return y + 22;
  };

  const rowHeightFor = (row) => {
    const particular = String(row?.[1] ?? "");
    const lines = Math.max(1, Math.ceil(particular.length / 46));
    return Math.min(44, Math.max(22, 13 + lines * 8));
  };

  let y = drawCenteredHeader();
  y = drawTableHeader(y);

  const rows = [];
  rows.push([
    "",
    `Opening Balance${financialYear ? ` (${financialYear})` : ""}`,
    "",
    "",
    summary?.openingDebit ? fmt(summary.openingDebit) : "",
    summary?.openingCredit ? fmt(summary.openingCredit) : "",
    { bold: true },
  ]);
  for (const row of entries || []) {
    rows.push([
      dateText(row?.date),
      row?.particular || partyName,
      row?.voucherType || row?.transactionType || "",
      row?.voucherNo || row?.transactionId || "",
      Number(row?.debit || 0) ? fmt(row.debit) : "",
      Number(row?.credit || 0) ? fmt(row.credit) : "",
      {},
    ]);
  }
  rows.push([
    "",
    "Closing Balance",
    "",
    "",
    summary?.showOnDebit ? fmt(summary.closingDiff) : "",
    summary?.showOnCredit ? fmt(summary.closingDiff) : "",
    { bold: true },
  ]);
  rows.push([
    "",
    "Total",
    "",
    "",
    fmt(summary?.balancedTotal || 0),
    fmt(summary?.balancedTotal || 0),
    { bold: true },
  ]);

  for (const row of rows) {
    const style = row[6] || {};
    const h = rowHeightFor(row);
    if (y + h > doc.page.height - 42) {
      doc.addPage();
      y = 34;
      doc.font("Helvetica-Bold").fontSize(9).fillColor("#374151")
        .text(`${partyName} - Ledger (${financialYear || ""})`, margin, y, { width: usableWidth, align: "center" });
      y = doc.y + 8;
      y = drawTableHeader(y);
    }
    let x = margin;
    for (let i = 0; i < 6; i += 1) {
      drawCell(row[i], x, y, widths[i], h, {
        bold: style.bold,
        align: i >= 4 ? "right" : i === 0 || i === 2 || i === 3 ? "center" : "left",
      });
      x += widths[i];
    }
    y += h;
  }

  doc.font("Helvetica").fontSize(7.5).fillColor("#6B7280")
    .text(`Closing: INR ${fmt(summary?.actualClosingBalance || 0)} ${summary?.actualClosingType || "DR"}`, margin, y + 8, { width: usableWidth, align: "right" });

  const pages = doc.bufferedPageRange();
  for (let i = 0; i < pages.count; i += 1) {
    doc.switchToPage(pages.start + i);
    doc.font("Helvetica").fontSize(7).fillColor("#9CA3AF")
      .text(`Page ${i + 1} of ${pages.count}`, margin, doc.page.height - 24, { width: usableWidth, align: "center" });
  }

  doc.end();
  return completed;
}

