import bcrypt from "bcryptjs";
import { connectDb } from "../config/db.js";
import { Plan, User, Role, Group, AccountTemplate, Branding, Hsn, Unit, Pincode, Product, Territory, GlobalCustomer, CustomerLink, CompanyProfile, CompanyLedger } from "../models/index.js";
import { makeId } from "../utils/ids.js";
import { defaultRoleTemplates, defaultRoleTemplateCodes, MASTER_TEMPLATE_TENANT } from "../config/defaultRoleTemplates.js";
import { allPermissionCodes } from "../config/permissionCatalogue.js";

await connectDb();
const email=process.env.SEED_MASTER_EMAIL||"master@rupioo.local";
const password=process.env.SEED_MASTER_PASSWORD||"ChangeMe123!";
const defaultGroupCode="DMS_COMPLETE";
const dmsPermissions=allPermissionCodes().filter(code=>String(code).startsWith("dms."));
await Group.findOneAndUpdate(
  {tenantKey:"demo",code:defaultGroupCode},
  {$set:{tenantKey:"demo",name:"DMS Complete Access",code:defaultGroupCode,description:"Default full DMS permission group for the COMPLETE plan",permissions:dmsPermissions,status:"ACTIVE"}},
  {upsert:true,new:true,setDefaultsOnInsert:true}
);
const existingCompletePlan=await Plan.findOne({code:"COMPLETE"}).lean();
const completeGroupCode=existingCompletePlan?.groupCode||defaultGroupCode;
await Plan.findOneAndUpdate({code:"COMPLETE"},{name:"Complete ERP",code:"COMPLETE",apps:{dms:true,hr:false,production:false},groupCode:completeGroupCode,roleTemplateCodes:defaultRoleTemplateCodes,monthlyAmount:0,yearlyAmount:0,addons:{otp:true,advancedGst:true,aiTargets:true,familyAccounts:true,barcode:true},limits:{users:null,employees:null,companies:null,warehouses:null,machines:null,storageGb:null,aiMonthly:null},status:"ACTIVE"},{upsert:true,new:true,setDefaultsOnInsert:true});
await User.findOneAndUpdate({email},{name:"Rupioo MASTER",email,passwordHash:await bcrypt.hash(password,12),role:"MASTER",apps:["master","dms"],permissions:["*"],planCode:"COMPLETE",tenantKey:"demo",status:"ACTIVE"},{upsert:true,new:true,setDefaultsOnInsert:true});
await Branding.findOneAndUpdate({key:"GLOBAL"},{slogan:"This page is generated by the Rupioo Global System.",website:"https://rupioo.com"},{upsert:true,new:true});
// MASTER role templates are created before any company/Superadmin.
// Each new company receives its own editable copy of the templates selected by its Plan.
for (const r of defaultRoleTemplates) {
  await Role.findOneAndUpdate(
    { tenantKey: MASTER_TEMPLATE_TENANT, code: r.code },
    { ...r, tenantKey: MASTER_TEMPLATE_TENANT, sourceTemplateCode: r.code, status: "ACTIVE" },
    { upsert: true, new: true, setDefaultsOnInsert: true }
  );

  // Keep the demo tenant usable for local development.
  await Role.findOneAndUpdate(
    { tenantKey: "demo", code: r.code },
    { ...r, tenantKey: "demo", sourceTemplateCode: r.code, status: "ACTIVE" },
    { upsert: true, new: true, setDefaultsOnInsert: true }
  );
}

const accounts=[
["SYS_BRANCH_DIVISION","Branch/Divisions","LIABILITY"],["SYS_CAPITAL","Capital Account","EQUITY"],["SYS_PROPRIETOR_CAPITAL","Proprietor Capital","EQUITY"],["SYS_PARTNER_CAPITAL","Partners Capital","EQUITY"],["SYS_PARTNER_CURRENT","Partners Current Accounts","LIABILITY"],["SYS_PARTNER_LOAN","Partner Loans","LIABILITY"],["SYS_DRAWINGS","Drawings","EQUITY"],["SYS_SHARE_CAPITAL","Share Capital","EQUITY"],["SYS_DIRECTOR_LOAN","Director Loans","LIABILITY"],["SYS_DIRECTOR_ADVANCE","Director Advances","ASSET"],["SYS_DIRECTOR_REMUNERATION","Director Remuneration Payable","LIABILITY"],["SYS_STAFF_ADVANCE","Staff Advances","ASSET"],["SYS_SALARY_PAYABLE","Salary Payable","LIABILITY"],["SYS_REIMBURSEMENT_PAYABLE","Reimbursement Payable","LIABILITY"],["SYS_CURRENT_ASSETS","Current Assets","ASSET"],["SYS_CURRENT_LIABILITIES","Current Liabilities","LIABILITY"],["SYS_DIRECT_EXPENSE","Direct Expenses","EXPENSE"],["SYS_DIRECT_INCOME","Direct Incomes","INCOME"],["SYS_FIXED_ASSETS","Fixed Assets","ASSET"],["SYS_INDIRECT_EXPENSE","Indirect Expenses","EXPENSE"],["SYS_INDIRECT_INCOME","Indirect Incomes","INCOME"],["SYS_INVESTMENT","Investments","ASSET"],["SYS_LOAN_LIABILITY","Loans (Liability)","LIABILITY"],["SYS_MISC_EXP_ASSET","Misc. Expenses (Asset)","ASSET"],["SYS_PURCHASE","Purchase Accounts","EXPENSE"],["SYS_SALES","Sales Accounts","INCOME"],["SYS_SUSPENSE","Suspense A/c","ASSET"],["SYS_BANK_ACCOUNT","Bank Accounts","ASSET"],["SYS_BANK_OD","Bank OD A/c","LIABILITY"],["SYS_CASH","Cash-in-hand","ASSET"],["SYS_DEPOSIT_ASSET","Deposits (Asset)","ASSET"],["SYS_DUTIES_TAXES","Duties & Taxes","LIABILITY"],["SYS_LOANS_ADVANCES","Loans & Advances (Asset)","ASSET"],["SYS_PROVISIONS","Provisions","LIABILITY"],["SYS_RESERVES_SURPLUS","Reserves & Surplus","EQUITY"],["SYS_SECURED_LOAN","Secured Loans","LIABILITY"],["SYS_STOCK","Stock-in-hand","ASSET"],["SYS_SUNDRY_CREDITORS","Sundry Creditors","LIABILITY"],["SYS_SUNDRY_DEBTORS","Sundry Debtors","ASSET"],["SYS_UNSECURED_LOAN","Unsecured Loans","LIABILITY"]
];
for(const [systemCode,name,nature] of accounts) await AccountTemplate.findOneAndUpdate({systemCode},{systemCode,name,nature,locked:true,allowCompanyLedger:["SYS_CAPITAL","SYS_PROPRIETOR_CAPITAL","SYS_PARTNER_CAPITAL","SYS_PARTNER_CURRENT","SYS_PARTNER_LOAN","SYS_DRAWINGS","SYS_SHARE_CAPITAL","SYS_DIRECTOR_LOAN","SYS_DIRECTOR_ADVANCE","SYS_DIRECTOR_REMUNERATION","SYS_STAFF_ADVANCE","SYS_SALARY_PAYABLE","SYS_REIMBURSEMENT_PAYABLE","SYS_BANK_ACCOUNT","SYS_FIXED_ASSETS","SYS_DIRECT_EXPENSE","SYS_INDIRECT_EXPENSE","SYS_INDIRECT_INCOME","SYS_LOAN_LIABILITY","SYS_LOANS_ADVANCES","SYS_SUNDRY_DEBTORS","SYS_SUNDRY_CREDITORS"].includes(systemCode),reportMap:{trading:["SYS_SALES","SYS_PURCHASE","SYS_DIRECT_EXPENSE","SYS_DIRECT_INCOME","SYS_STOCK"].includes(systemCode),pnl:["INCOME","EXPENSE"].includes(nature),balanceSheet:["ASSET","LIABILITY","EQUITY"].includes(nature),cma:true}},{upsert:true,new:true});

const accountParents={
  SYS_PROPRIETOR_CAPITAL:"SYS_CAPITAL",SYS_PARTNER_CAPITAL:"SYS_CAPITAL",SYS_PARTNER_CURRENT:"SYS_CURRENT_LIABILITIES",SYS_PARTNER_LOAN:"SYS_LOAN_LIABILITY",SYS_DRAWINGS:"SYS_CAPITAL",SYS_SHARE_CAPITAL:"SYS_CAPITAL",
  SYS_DIRECTOR_LOAN:"SYS_LOAN_LIABILITY",SYS_DIRECTOR_ADVANCE:"SYS_LOANS_ADVANCES",SYS_DIRECTOR_REMUNERATION:"SYS_CURRENT_LIABILITIES",SYS_STAFF_ADVANCE:"SYS_LOANS_ADVANCES",SYS_SALARY_PAYABLE:"SYS_CURRENT_LIABILITIES",SYS_REIMBURSEMENT_PAYABLE:"SYS_CURRENT_LIABILITIES"
};
for(const [systemCode,parentCode] of Object.entries(accountParents)) await AccountTemplate.updateOne({systemCode},{$set:{parentCode,allowCompanyLedger:true}});

await CompanyProfile.findOneAndUpdate({tenantKey:"demo"},{tenantKey:"demo",companyName:"Demo Company",tradeName:"Rupioo Demo",companyType:"PROPRIETORSHIP",financialYear:"2026-27",stakeholders:[{stakeholderId:"STK-DEMO-OWNER",name:"Demo Owner",roleType:"PROPRIETOR",openingCapital:0,active:true,accountingRelationships:[{relationshipType:"CAPITAL",systemAccountCode:"SYS_PROPRIETOR_CAPITAL",ledgerName:"Demo Owner - Capital A/c",openingBalance:0,openingBalanceType:"CR",financialYear:"2026-27",status:"ACTIVE"}]}],status:"ACTIVE",createdBy:"seed"},{upsert:true,new:true,setDefaultsOnInsert:true});
await CompanyLedger.findOneAndUpdate({tenantKey:"demo",ownerType:"STAKEHOLDER",ownerId:"STK-DEMO-OWNER",relationshipType:"CAPITAL",systemAccountCode:"SYS_PROPRIETOR_CAPITAL"},{tenantKey:"demo",ledgerId:"LED-DEMO-OWNER-CAPITAL",ownerType:"STAKEHOLDER",ownerId:"STK-DEMO-OWNER",relationshipType:"CAPITAL",systemAccountCode:"SYS_PROPRIETOR_CAPITAL",name:"Demo Owner - Capital A/c",openingBalances:[{financialYear:"2026-27",amount:0,type:"CR"}],status:"ACTIVE",createdFrom:"SEED"},{upsert:true,new:true,setDefaultsOnInsert:true});
await Hsn.findOneAndUpdate({code:"DEMO-18"},{code:"DEMO-18",description:"Demo HSN - replace/sync with statutory source",gstRate:18,cgstRate:9,sgstRate:9,igstRate:18,status:"ACTIVE"},{upsert:true,new:true});
for(const u of [{code:"PCS",name:"Pieces",uqc:"PCS",decimals:0},{code:"KG",name:"Kilogram",uqc:"KGS",decimals:3},{code:"BOX",name:"Box",uqc:"BOX",decimals:0},{code:"CTN",name:"Carton",uqc:"CTN",decimals:0},{code:"MTR",name:"Metre",uqc:"MTR",decimals:3}]) await Unit.findOneAndUpdate({code:u.code},{...u,status:"ACTIVE"},{upsert:true,new:true});
for(const p of [{pincode:"781001",area:"Pan Bazaar",city:"Guwahati",district:"Kamrup Metropolitan",state:"Assam"},{pincode:"781028",area:"Beltola",city:"Guwahati",district:"Kamrup Metropolitan",state:"Assam"}]) await Pincode.findOneAndUpdate({pincode:p.pincode},p,{upsert:true,new:true});
const territory=await Territory.findOneAndUpdate({tenantKey:"demo",name:"Guwahati Central"},{tenantKey:"demo",name:"Guwahati Central",pincodes:["781001","781028"],userId:"demo-sales-1",managerId:"demo-manager",status:"ACTIVE"},{upsert:true,new:true});
for(const p of [{sku:"EKO-SP160-100",name:"Bio Spoon 160 mm - 100 pcs",category:"Cutlery",landedCost:100,salePrice:114,minimumProfitPct:5},{sku:"EKO-CB12",name:"Cake Base 12 inch",category:"Cake Base",landedCost:50,salePrice:61,minimumProfitPct:8},{sku:"EKO-GB-L",name:"Garbage Bag Large",category:"Garbage Bags",landedCost:80,salePrice:84,minimumProfitPct:3}]) await Product.findOneAndUpdate({tenantKey:"demo",sku:p.sku},{...p,tenantKey:"demo",hsnCode:"DEMO-18",unit:"PCS"},{upsert:true,new:true});
const global=await GlobalCustomer.findOneAndUpdate({pan:"ABCDE1234F"},{hiddenId:makeId("GC"),legalName:"ABC Traders",customerType:"BUSINESS",pan:"ABCDE1234F",gstins:[{value:"18ABCDE1234F1Z5",state:"Assam",status:"ACTIVE",verifiedAt:new Date()}],mobiles:[{value:"9876543210",verified:true,primary:true}],emails:[{value:"accounts@abctraders.example",verified:true,primary:true}],globalHealth:{score:84,grade:"B",color:"BLUE",confidence:"HIGH",updatedAt:new Date()},linkedTenants:[{tenantKey:"demo",linkedAt:new Date()}]},{upsert:true,new:true,setDefaultsOnInsert:true});
await CustomerLink.findOneAndUpdate({tenantKey:"demo",globalCustomerId:global.hiddenId},{tenantKey:"demo",globalCustomerId:global.hiddenId,displayIdentifier:"18ABCDE1234F1Z5",localName:"ABC Traders",paymentType:"CREDIT",creditDays:30,creditLimit:500000,status:"ACTIVE",territoryId:territory._id.toString(),verification:{identity:true,mobile:true,email:true,gps:true,kyc:true,appLinked:false},companyHealth:{score:78,grade:"B",color:"BLUE",updatedAt:new Date()}},{upsert:true,new:true,setDefaultsOnInsert:true});
console.log(`Seed complete. Login: ${email} / ${password}`);
process.exit(0);
