import mongoose from "mongoose";

const { Schema } = mongoose;
const getModel = (name, schema) => mongoose.models[name] || mongoose.model(name, schema);

const contactSchema = new Schema({
  name: String,
  mobile: String,
  email: String,
}, { _id: false });

const vendorSnapshotSchema = new Schema({
  vendorGlobalId: { type: String, index: true },
  vendorName: String,
  gstin: String,
  mobile: String,
  email: String,
  lastPurchaseDate: Date,
  lastInvoiceNo: String,
  lastRate: Number,
  lastQty: Number,
  avgRate: Number,
  purchaseCount: Number,
  creditDays: Number,
  score: Number,
  reason: String,
}, { _id: false });

const requirementItemSchema = new Schema({
  productId: { type: String, index: true },
  sku: String,
  productName: String,
  hsnCode: String,
  unit: String,
  currentStock: Number,
  reservedStock: Number,
  availableStock: Number,
  incomingPoQty: Number,
  effectiveStock: Number,
  trendClass: String,
  triggerPct: Number,
  targetStock: Number,
  triggerQty: Number,
  avgDaily30: Number,
  avgDaily90: Number,
  salesQty30: Number,
  salesQty90: Number,
  forecast30: Number,
  safetyStock: Number,
  suggestedQty: Number,
  requestedQty: Number,
  quantitySource: { type: String, enum: ["AI", "MANUAL"], default: "AI" },
  moq: Number,
  orderMultiple: Number,
  leadDays: Number,
  primaryVendorGlobalId: String,
  primaryVendorName: String,
  primaryVendorLastRate: Number,
}, { _id: false });

const purchaseRequirementSchema = new Schema({
  tenantKey: { type: String, required: true, index: true },
  financialYear: { type: String, required: true, index: true },
  requirementNo: { type: String, required: true, index: true },
  productId: { type: String, required: true, index: true },
  sku: String,
  productName: String,
  hsnCode: String,
  unit: String,
  trendClass: { type: String, enum: ["HIGH", "MEDIUM", "LOW"], index: true },
  triggerPct: Number,
  targetStock: Number,
  triggerQty: Number,
  currentStock: Number,
  reservedStock: Number,
  availableStock: Number,
  pendingPoQty: Number,
  effectiveStock: Number,
  avgDaily30: Number,
  avgDaily90: Number,
  salesQty30: Number,
  salesQty90: Number,
  forecast30: Number,
  safetyStock: Number,
  suggestedQty: Number,
  requestedQty: Number,
  moq: Number,
  orderMultiple: Number,
  leadDays: Number,
  aiReason: String,
  lastPurchase: {
    date: Date,
    invoiceNo: String,
    rate: Number,
    landedRate: Number,
    qty: Number,
    vendorGlobalId: String,
    vendorName: String,
    gstin: String,
    mobile: String,
    email: String,
  },
  vendorSuggestions: [vendorSnapshotSchema],
  draftItems: [requirementItemSchema],
  status: {
    type: String,
    enum: ["TRIGGERED", "ORDER_SHEET", "RFQ_SENT", "PO_CREATED", "HOLD", "IGNORED", "CLOSED"],
    default: "TRIGGERED",
    index: true,
  },
  holdUntil: Date,
  holdReason: String,
  scanVersion: Number,
  lastTriggeredAt: Date,
  generatedAt: Date,
  createdBy: String,
  updatedBy: String,
}, { timestamps: true });
purchaseRequirementSchema.index({ tenantKey: 1, productId: 1, status: 1 });
purchaseRequirementSchema.index({ tenantKey: 1, requirementNo: 1 }, { unique: true });

const quoteItemSchema = new Schema({
  productId: String,
  sku: String,
  productName: String,
  qty: Number,
  unit: String,
  rate: Number,
  discountPct: Number,
  gstRate: Number,
  freight: Number,
  landedRate: Number,
  deliveryDays: Number,
  remarks: String,
}, { _id: false });

const rfqVendorSchema = new Schema({
  vendorGlobalId: { type: String, index: true },
  vendorName: String,
  gstin: String,
  contact: contactSchema,
  status: { type: String, default: "SENT", index: true },
  sentAt: Date,
  viewedAt: Date,
  submittedAt: Date,
  quoteNo: String,
  quoteDate: Date,
  validityDate: Date,
  creditDays: Number,
  freightTerms: String,
  overallFreight: Number,
  expectedDispatchDate: Date,
  expectedDeliveryDate: Date,
  quoteItems: [quoteItemSchema],
  quotationFileIds: [String],
  aiExtractionId: String,
  totalTaxable: Number,
  totalTax: Number,
  grandTotal: Number,
  landedTotal: Number,
  vendorRemarks: String,
  comparisonScore: Number,
  comparisonReasons: [String],
}, { _id: true });

const purchaseRfqSchema = new Schema({
  tenantKey: { type: String, required: true, index: true },
  financialYear: { type: String, required: true, index: true },
  rfqNo: { type: String, required: true, index: true },
  requirementIds: [{ type: String, index: true }],
  items: [requirementItemSchema],
  vendors: [rfqVendorSchema],
  selectedVendorGlobalId: { type: String, index: true },
  selectedVendorReason: String,
  status: { type: String, default: "OPEN", index: true },
  requiredByDate: Date,
  deliveryLocation: String,
  remarks: String,
  createdBy: String,
  awardedBy: String,
  awardedAt: Date,
}, { timestamps: true });
purchaseRfqSchema.index({ tenantKey: 1, rfqNo: 1 }, { unique: true });

const poItemSchema = new Schema({
  productId: { type: String, index: true },
  sku: String,
  productName: String,
  hsnCode: String,
  unit: String,
  orderedQty: Number,
  confirmedQty: Number,
  dispatchedQty: Number,
  receivedQty: Number,
  acceptedQty: Number,
  rejectedQty: Number,
  shortQty: Number,
  damagedQty: Number,
  rate: Number,
  discountPct: Number,
  gstRate: Number,
  freight: Number,
  landedRate: Number,
  lineTaxable: Number,
  lineTax: Number,
  lineTotal: Number,
}, { _id: false });

const shipmentSchema = new Schema({
  shipmentNo: String,
  invoiceNo: String,
  invoiceDate: Date,
  invoiceAmount: Number,
  invoiceFileIds: [String],
  lrNo: String,
  lrDate: Date,
  lrFileIds: [String],
  transporterName: String,
  transporterId: String,
  vehicleNo: String,
  fromLocation: String,
  destination: String,
  packages: Number,
  weight: Number,
  freight: Number,
  freightMode: String,
  dispatchDate: Date,
  dispatchTime: String,
  expectedArrival: Date,
  items: [{ productId: String, qty: Number, _id: false }],
  aiExtractionIds: [String],
  status: { type: String, default: "DISPATCHED" },
  submittedAt: Date,
}, { _id: true });

const purchaseOrderSchema = new Schema({
  tenantKey: { type: String, required: true, index: true },
  financialYear: { type: String, required: true, index: true },
  poNo: { type: String, required: true, index: true },
  rfqId: { type: String, index: true },
  rfqNo: String,
  requirementIds: [String],
  vendorGlobalId: { type: String, required: true, index: true },
  vendorName: String,
  vendorGstin: String,
  vendorContact: contactSchema,
  items: [poItemSchema],
  totalTaxable: Number,
  totalTax: Number,
  grandTotal: Number,
  landedTotal: Number,
  creditDays: Number,
  paymentTerms: String,
  deliveryLocation: String,
  requiredByDate: Date,
  status: { type: String, default: "PO_SENT", index: true },
  supplierConfirmation: {
    accepted: Boolean,
    confirmedAt: Date,
    expectedDispatchDate: Date,
    expectedDispatchTime: String,
    expectedArrivalDate: Date,
    remarks: String,
  },
  shipments: [shipmentSchema],
  accountingStatus: { type: String, default: "NOT_READY", index: true },
  paymentStatus: { type: String, default: "NOT_DUE", index: true },
  paymentDueDate: Date,
  paymentReference: String,
  paymentDate: Date,
  createdBy: String,
  updatedBy: String,
}, { timestamps: true });
purchaseOrderSchema.index({ tenantKey: 1, poNo: 1 }, { unique: true });
purchaseOrderSchema.index({ tenantKey: 1, vendorGlobalId: 1, status: 1, updatedAt: -1 });

const qcItemSchema = new Schema({
  productId: String,
  sku: String,
  productName: String,
  dispatchedQty: Number,
  receivedQty: Number,
  acceptedQty: Number,
  damagedQty: Number,
  rejectedQty: Number,
  shortQty: Number,
  excessQty: Number,
  wrongProductQty: Number,
  remarks: String,
  evidenceFileIds: [String],
}, { _id: false });

const goodsReceiptSchema = new Schema({
  tenantKey: { type: String, required: true, index: true },
  financialYear: { type: String, required: true, index: true },
  grnNo: { type: String, required: true, index: true },
  purchaseOrderId: { type: String, required: true, index: true },
  poNo: String,
  shipmentId: String,
  vendorGlobalId: { type: String, index: true },
  vendorName: String,
  arrivedAt: Date,
  warehouseId: String,
  warehouseName: String,
  dispatchedPackages: Number,
  receivedPackages: Number,
  packageCondition: [{ packageNo: String, condition: String, remarks: String, evidenceFileIds: [String], _id: false }],
  items: [qcItemSchema],
  generalEvidenceFileIds: [String],
  qcStatus: { type: String, default: "IN_PROGRESS", index: true },
  qcCompletedAt: Date,
  qcCompletedBy: String,
  warehouseOtpId: String,
  warehouseOtpVerifiedAt: Date,
  inwardedAt: Date,
  inwardedBy: String,
  purchaseInvoiceId: String,
  purchaseInvoiceNo: String,
  accountingStatus: { type: String, default: "NOT_READY", index: true },
  remarks: String,
}, { timestamps: true });
goodsReceiptSchema.index({ tenantKey: 1, grnNo: 1 }, { unique: true });

const purchaseComplaintSchema = new Schema({
  tenantKey: { type: String, required: true, index: true },
  complaintNo: { type: String, required: true, index: true },
  purchaseOrderId: { type: String, required: true, index: true },
  poNo: String,
  grnId: { type: String, index: true },
  grnNo: String,
  vendorGlobalId: { type: String, required: true, index: true },
  vendorName: String,
  supplierInvoiceNo: String,
  issueType: { type: String, index: true },
  title: String,
  description: String,
  items: [qcItemSchema],
  evidenceFileIds: [String],
  status: { type: String, default: "OPEN", index: true },
  requestedResolution: String,
  vendorResponse: {
    action: String,
    remarks: String,
    promisedDate: Date,
    responseFileIds: [String],
    respondedAt: Date,
  },
  creditNote: {
    creditNoteNo: String,
    date: Date,
    taxableValue: Number,
    tax: Number,
    total: Number,
    fileIds: [String],
    aiExtractionId: String,
  },
  timeline: [{ at: { type: Date, default: Date.now }, byType: String, byId: String, action: String, note: String, _id: false }],
  createdBy: String,
  closedAt: Date,
  closedBy: String,
}, { timestamps: true });
purchaseComplaintSchema.index({ tenantKey: 1, complaintNo: 1 }, { unique: true });

const purchaseDocumentSchema = new Schema({
  tenantKey: { type: String, required: true, index: true },
  vendorGlobalId: { type: String, index: true },
  documentId: { type: String, required: true, unique: true, index: true },
  documentType: { type: String, required: true, index: true },
  scopeType: String,
  scopeId: String,
  fileId: String,
  originalName: String,
  mimeType: String,
  extractionEngine: String,
  extraction: Schema.Types.Mixed,
  confirmedValues: Schema.Types.Mixed,
  confirmedAt: Date,
  status: { type: String, default: "EXTRACTED", index: true },
  createdByType: String,
  createdBy: String,
}, { timestamps: true });

const vendorPortalAccessSchema = new Schema({
  tenantKey: { type: String, required: true, index: true },
  vendorGlobalId: { type: String, required: true, index: true },
  version: { type: Number, default: 1 },
  active: { type: Boolean, default: true, index: true },
  lastUsedAt: Date,
  lastIp: String,
}, { timestamps: true });
vendorPortalAccessSchema.index({ tenantKey: 1, vendorGlobalId: 1 }, { unique: true });

export const PurchaseRequirement = getModel("PurchaseRequirement", purchaseRequirementSchema);
export const PurchaseRfq = getModel("PurchaseRfq", purchaseRfqSchema);
export const PurchaseOrder = getModel("PurchaseOrderAi", purchaseOrderSchema);
export const PurchaseGoodsReceipt = getModel("PurchaseGoodsReceipt", goodsReceiptSchema);
export const PurchaseComplaint = getModel("PurchaseComplaint", purchaseComplaintSchema);
export const PurchaseDocument = getModel("PurchaseDocument", purchaseDocumentSchema);
export const VendorPortalAccess = getModel("VendorPortalAccess", vendorPortalAccessSchema);
